#=====================================================================
# MySQL Dockerfile
#---------------------------------------------------------------------
# docker/containers/mysql/Dockerfile
#=====================================================================

# Install MySQL
FROM mysql:5.7.22

# Copy MySQL configuration
COPY ./containers/mysql/conf.d/my.cnf /etc/mysql/conf.d/my.cnf

EXPOSE 3306
