name: CI Build

on:
  push:
    # Integration / Deployment runs ONLY when code lands on the main branch.
    branches: [ "master" ]
  pull_request:
    # Validation runs when a PR is created, checks code quality and tests.
    branches: [ "master", "development" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      # Git Checkout
    - name: Checkout Code
      uses: actions/checkout@v4

    # Docker Credentials
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_KEY }}

    # Setting Script Permissions
    - name: Setting up Permissions
      run: |
        chmod +x -R ./scripts/*.sh
        # mkdir -p ./storage/logs/ ./bootstrap/cache/ # Skipping, there is no dir structure yet
        # chmod 777 ./storage/ ./bootstrap/cache -R   # Yup, same with this one

    # Building Docker Images and Service Containers
    - name: Building Docker Images
      run: ./scripts/build.sh

    # Docker Containers
    - name: Start Docker Containers
      run: ./scripts/up.sh -d

    # Teardown routine, clean after yourself!
    - name: Teardown, stopping and removing services
      if: always()
      run: ./scripts/down.sh -v
